### ISSUE TITLE
"texture" bottom is flip horizontally

### ISSUE THREAD

**Issue by kikipunk** [Godlander/tooltip#1]
Hi, happy new year

"texture" bottom is flip horizontally

Exemple:
![image](https://github.com/Godlander/tooltip/assets/7613740/7c0a207f-4f8b-423a-9612-7ff5eacf654f)
 is render
![image](https://github.com/Godlander/tooltip/assets/7613740/94785e01-2748-4c81-bc05-a3c05c5cfe26)

(the error is not the python script)

I'm bad in shader but on gui.fsh line 42 (this is work)
`                i = ((sizes.x-(side.x*-1)))   + (sizes.z-corner.w-2) * sizes.x; color = hex(b[i]); break;`

**Comment by Godlander** [comment]
o, nice catch, thanks

i only tested with mirrored texture so it didn't matter
