### ISSUE TITLE
Repository License

### ISSUE THREAD

**Issue by jevexendo** [Godlander/tooltip#4]
Since this repository is currently unlicensed it is technically a copyright violation to use, change, or distribute any of the resources provided here (See [Licensing a Repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) for more information).

Since I believe your intent is to make this a public resource, it would be appreciated if you were to make the usage of this repository explicitly legal by adding a LICENSE file with whichever license that best describes your intentions.

Thank you for your consideration, and please feel free to ask me any questions you might have.

**Comment by Godlander** [comment]
added mit license
