### ISSUE TITLE
Sky vision problem

### ISSUE THREAD

**Issue by notfifteen** [Godlander/tooltip#6]
Hi, I am using the script to generate the toolip and it works perfect, thanks for the resource, it really looks great, but I have noticed that the same design or color of the toolip can be seen in the sky when it is night time. 
![Screenshot_1](https://github.com/Godlander/tooltip/assets/75852372/e48e4015-92ab-4cdf-9374-f6608ea3f4f2)
![Screenshot_2](https://github.com/Godlander/tooltip/assets/75852372/02197f2c-bf91-4487-8de6-fef287c44dbe)

**Comment by notfifteen** [comment]
server is running Paper version git-Paper-389 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 848a396)

**Comment by Godlander** [comment]
can you reproduce in vanilla singleplayer

if so, please put some instructions to reproduce, i.e. exact time of day, if it happens in a void world, if it only happens with that particular tooltip image, etc

**Comment by Godlander** [comment]
should be fixed in latest
