### ISSUE TITLE
Incompatibility with lunar client?

### ISSUE THREAD

**Issue by notfifteen** [Godlander/tooltip#8]
Hello, I don't know much about this, that's why I wanted to ask, the shader for the tooltip does not work in lunarclient, it becomes completely invisible, any solution to this?

Vanilla client:
https://imgur.com/2axCxkl

LunarClient
https://imgur.com/gPqUEWl

**Comment by Godlander** [comment]
if lunar client is incompatible with a vanilla feature thats their issue. not something i can fix

**Comment by ChloeDawn** [comment]
I am experiencing a similar issue on the [Minebox](https://minebox.co/) servers. It only affects some tooltips, and I am not using Lunar Client, it is vanilla Minecraft launched through Prism Launcher. An OpenGL error is printed every frame whilst in the server.

`Unknown NIR alu instr: div 32    %133 = ineg %66`

**Log file (with errors truncated):** https://mclo.gs/it9jOiU

**Example of a tooltip failing to render:**

![Tooltip with no background](https://github.com/user-attachments/assets/8ad0044d-187d-4a1f-b3ed-19330e2c9b3d)

**Example of another tooltip that renders normally:**

![Tooltip with background](https://github.com/user-attachments/assets/5db6bee6-88b9-4d24-80bd-6c577b7c03a2)

**Comment by Godlander** [comment]
since the snapshots introduced actual 9 slice tooltip textures in resourcepack, this tool is basically rendered obsolete
